// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'Spell.freezed.dart';
part 'Spell.g.dart';

@freezed
class Spell with _$Spell {
  const factory Spell({
    required String spellName,
    required String description,
    required int spellType,
  }) = _Spell;

  factory Spell.fromJson(Map<String, Object?> json) => _$SpellFromJson(json);
}
